### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by WowieMan** [xan-m/InfiniLink#34]
Not sure if you’re looking for a new icon, but if you are, I've created one you can use.

![image](https://user-images.githubusercontent.com/87885710/135333641-c166abdd-104d-4c70-bdce-8e9596726bae.png)

If you need it in a different format, like ￼.SVG, I can send that.

**Comment by xan-m** [comment]
Wow, thank you! I love it! I just threw together the existing logo because I had to have something to submit it to TestFlight, but this is obviously much higher quality.

XCode makes you manually create 18 differently-sized png files ranging from 1024x1024 px to 20x20 px, so SVG would be great if it's not too much trouble!

**Comment by LittleDuck702** [comment]
Sure, no trouble at all.

[](https://drive.google.com/drive/folders/1Ubz2pI20p8uBQR2VEIRmi65Xbva-X1Qk)

**Comment by xan-m** [comment]
Awesome, I'll add this to the next version! Thanks again!

I'm going to leave this open for now so I remember to add it before shipping the next version :)

**Comment by xan-m** [comment]
Sorry for the huge delay on this, it kept slipping my mind before releasing each version. It's added to the app now, and will be the icon for 9.3.0 on!
