### ISSUE TITLE
InfiniTime latest release not detected

### ISSUE THREAD

**Issue by onigiri070** [xan-m/InfiniLink#44]
InfiniLink is not detecting the latest available release of InfiniTime (1.7.0) for me. It sees version 1.6 and updates smoothly but doesn't see the 1.7 release. 

Experiencing this behavior on InfiniLink 0.9.3.

**Comment by xan-m** [comment]
Interesting, it is showing up on mine. Does the little refresh button at the top of the “download firmware file” pop-up sheet help? I turned the GitHub API checks way down to avoid hitting rate limits, so perhaps it hasn’t refreshed that list since 1.7.0?
![AF9269E2-6F8B-4F4D-B304-C9CF374427A3](https://user-images.githubusercontent.com/88455615/141689140-36fab325-5fa5-45d2-a536-e63a0748d5ed.jpeg)

**Comment by onigiri070** [comment]
Ah, my apologies. I hadn't tried checking the "Select Firmware File" option so I didn't see the Download option. I stupidly assumed that option meant selecting a local file so I didn't even think to look there. 

Many apologies and thanks for correcting my mistake!

**Comment by xan-m** [comment]
No worries! It's definitely not super apparent at first glance. I'm assuming 1.7.0 did show up there after all and we're good to close this?

**Comment by onigiri070** [comment]
We're good to close!

**Comment by xan-m** [comment]
Thank you!
